version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "google-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1swodod7gwogn"
s3_prefix = "google-api"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
